import { readFile, writeFile } from 'node:fs/promises';

const root = new URL('../', import.meta.url);
const read = path => readFile(new URL(path, root), 'utf8');
export async function buildMapDocument() {
  const [js, css, runtime, styles, license] = await Promise.all([
    read('node_modules/leaflet/dist/leaflet.js'), read('node_modules/leaflet/dist/leaflet.css'),
    read('src/map/map-runtime.js'), read('src/map/map.css'), read('node_modules/leaflet/LICENSE'),
  ]);
  let bundledCss = css;
  for (const name of ['layers.png', 'layers-2x.png', 'marker-icon.png']) {
    const bytes = await readFile(new URL(`node_modules/leaflet/dist/images/${name}`, root));
    bundledCss = bundledCss.replaceAll(`url(images/${name})`, `url(data:image/png;base64,${bytes.toString('base64')})`);
  }
  const escapeScript = value => value.replace(/<\/script/gi, '<\\/script');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"><title>Workable BCN map</title><style>${bundledCss}\n${styles}</style></head><body><div id="map" aria-label="Cafés in Barcelona"></div><div id="tile-error" role="status" hidden>The map could not load. Check your connection. Addresses are still available in the list.</div><script>/* ${license.replaceAll('*/', '* /')} */\n${escapeScript(js.replace(/\/\/# sourceMappingURL=.*$/m, ''))}</script><script>${escapeScript(runtime)}</script></body></html>`;
}
export async function generatedMapSource() {
  return '// Generated by npm run map:build. Includes Leaflet under its BSD-2-Clause license.\nexport const mapHtml = ' + JSON.stringify(await buildMapDocument()) + ';\n';
}
if (process.argv.includes('--write')) {
  await writeFile(new URL('src/map/map-html.ts', root), await generatedMapSource());
  console.log('Bundled Leaflet, CSS images, and map runtime into src/map/map-html.ts');
}
